/* eslint-disable n8n-nodes-base/node-filename-against-convention */
import { INodeTypeDescription } from 'n8n-workflow';

export const nodeDescription: INodeTypeDescription = {
	displayName: 'Apollo.io',
	name: 'apolloIo',
	icon: 'file:Apollo.svg',
	group: ['resource'],
	version: 1,
	description: 'Interact with the Apollo.io API',
	defaults: {
		name: 'Apollo.io',
	},
	inputs: ['main'],
	outputs: ['main'],
	credentials: [
		{
			name: 'apolloApi',
			required: true,
		},
	],
	properties: [
		{
			displayName: 'Resource',
			name: 'resource',
			type: 'options',
			options: [
				{ name: 'Sequence', value: 'sequence' },
				{ name: 'Person', value: 'person' },
				{ name: 'Organization', value: 'organization' },
			],
			default: 'sequence',
			noDataExpression: true,
		},
		// Operations for Sequence
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['sequence'] } },
			options: [
				{ name: 'Search', value: 'search', action: 'Search a sequence' },
				{ name: 'Add Contacts', value: 'addContacts', action: 'Add contacts a sequence' },
			],
			default: 'search',
			noDataExpression: true,
			required: true,
		},
		// Operations for Person
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['person'] } },
			options: [
				{ name: 'Enrich', value: 'enrich', action: 'Enrich a person' },
				{ name: 'Bulk Enrich', value: 'bulkEnrich', action: 'Bulk enrich a person' },
				{ name: 'Search', value: 'search', action: 'Search for people' },
			],
			default: 'enrich',
			noDataExpression: true,
			required: true,
		},
		// Operations for Organization
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['organization'] } },
			options: [
				{ name: 'Enrich', value: 'enrich', action: 'Enrich an organization' },
				{ name: 'Bulk Enrich', value: 'bulkEnrich', action: 'Bulk enrich an organization' },
				{ name: 'Search', value: 'search', action: 'Search for organizations' },
			],
			default: 'enrich',
			noDataExpression: true,
			required: true,
		},
		// Fields for Sequence Search
		{
			displayName: 'Sequence Name Contains',
			name: 'sequenceName',
			type: 'string',
			default: '',
			description: 'Filter sequences by name containing this text',
			displayOptions: { show: { resource: ['sequence'], operation: ['search'] } },
		},
		{
			displayName: 'Page',
			name: 'page',
			type: 'number',
			default: 1,
			description: 'Page number of results',
			typeOptions: { minValue: 1 },
			displayOptions: { show: { resource: ['sequence'], operation: ['search'] } },
		},
		{
			displayName: 'Per Page',
			name: 'perPage',
			type: 'number',
			default: 25,
			description: 'Results per page (max 100)',
			typeOptions: { minValue: 1, maxValue: 100 },
			displayOptions: { show: { resource: ['sequence'], operation: ['search'] } },
		},
		// Fields for Sequence Add Contacts
		{
			displayName: 'Sequence ID',
			name: 'sequenceId',
			type: 'string',
			default: '',
			description: 'ID of the sequence to add contacts to',
			required: true,
			displayOptions: { show: { resource: ['sequence'], operation: ['addContacts'] } },
		},
		{
			displayName: 'Contact IDs',
			name: 'contactIds',
			type: 'string',
			default: '',
			description: 'Comma-separated list or JSON array of Apollo Contact IDs',
			placeholder: '5f...,6a... or ["5f...","6a..."]',
			required: true,
			displayOptions: { show: { resource: ['sequence'], operation: ['addContacts'] } },
		},
		// Fields for Person Enrich
		{
			displayName: 'Requirements',
			type: 'notice',
			name: 'personEnrichNotice',
			default: '',
			description:
				'Provide Email, LinkedIn URL, Apollo Person ID, or First Name + Last Name + Company Domain',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'Email',
			name: 'personEmail',
			type: 'string',
			default: '',
			placeholder: 'name@example.com',
			description: 'Email of the person to enrich',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'LinkedIn URL',
			name: 'personLinkedInUrl',
			type: 'string',
			default: '',
			placeholder: 'https://www.linkedin.com/in/...',
			description: 'LinkedIn profile URL of the person',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'Apollo Person ID',
			name: 'personId',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'First Name',
			name: 'personFirstName',
			type: 'string',
			default: '',
			description: 'First name of the person',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'Last Name',
			name: 'personLastName',
			type: 'string',
			default: '',
			description: 'Last name of the person',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		{
			displayName: 'Company Domain',
			name: 'personDomain',
			type: 'string',
			default: '',
			description: 'Domain of the person’s company',
			displayOptions: { show: { resource: ['person'], operation: ['enrich'] } },
		},
		// Fields for Person Bulk Enrich
		{
			displayName: 'People Details (JSON Array)',
			name: 'peopleDetailsJson',
			type: 'json',
			default: '[{"email":"name@example.com"}]',
			description: 'JSON array of up to 10 people objects with required identifiers',
			required: true,
			displayOptions: {
				show: { resource: ['person'], operation: ['bulkEnrich'] },
			},
		},
		// Fields for Person Search
		{
			displayName: 'Person Titles',
			name: 'personTitles',
			type: 'string',
			default: '',
			description: 'Job titles to filter by (semicolon separated)',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Keywords',
			name: 'qKeywords',
			type: 'string',
			default: '',
			description: 'Keywords to filter by',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Person Locations',
			name: 'personLocations',
			type: 'string',
			default: '',
			description: 'Locations to filter by (semicolon separated)',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Seniorities',
			name: 'personSeniorities',
			type: 'multiOptions',
			options: [
				{ name: 'C-Suite', value: 'c_suite' },
				{ name: 'Director', value: 'director' },
				{ name: 'Entry', value: 'entry' },
				{ name: 'Founder', value: 'founder' },
				{ name: 'Head', value: 'head' },
				{ name: 'Intern', value: 'intern' },
				{ name: 'Manager', value: 'manager' },
				{ name: 'Owner', value: 'owner' },
				{ name: 'Partner', value: 'partner' },
				{ name: 'Senior', value: 'senior' },
				{ name: 'VP', value: 'vp' },
			],
			default: [],
			description: 'Job seniority levels to filter by',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Organization Locations',
			name: 'organizationLocations',
			type: 'string',
			default: '',
			description: 'Company HQ locations (semicolon separated)',
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Organization Domains',
			name: 'organizationDomains',
			type: 'string',
			default: '',
			description: 'Company domains (semicolon separated)',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Email Status',
			name: 'contactEmailStatus',
			type: 'multiOptions',
			options: [
				{ name: 'Likely to Engage', value: 'likely to engage' },
				{ name: 'Unavailable', value: 'unavailable' },
				{ name: 'Unverified', value: 'unverified' },
				{ name: 'Verified', value: 'verified' },
			],
			default: [],
			description: 'Email statuses to filter by',
			displayOptions: { show: { resource: ['person'], operation: ['search'] } },
		},
		{
			displayName: 'Organization IDs',
			name: 'organizationIds',
			type: 'string',
			default: '',
			description: 'Apollo Organization IDs (semicolon separated)',
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Employee Count Ranges',
			name: 'organizationNumEmployeesRanges',
			type: 'string',
			default: '',
			description: 'Employee count ranges (semicolon separated, e.g. "1,10; 11,50")',
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Min Revenue',
			name: 'revenueRangeMin',
			type: 'number',
			default: 0,
			description: 'Minimum revenue of the employer',
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Max Revenue',
			name: 'revenueRangeMax',
			type: 'number',
			default: 0,
			description: 'Maximum revenue of the employer',
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Page',
			name: 'page',
			type: 'number',
			default: 1,
			description: 'Page number of results',
			typeOptions: { minValue: 1 },
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		{
			displayName: 'Per Page',
			name: 'perPage',
			type: 'number',
			default: 10,
			description: 'Number of results per page (max 100)',
			typeOptions: { minValue: 1, maxValue: 100 },
			displayOptions: {
				show: {
					resource: ['person', 'organization'],
					operation: ['search'],
				},
			},
		},
		// Fields for Organization Search
		{
			displayName: 'Excluded Locations',
			name: 'organizationNotLocations',
			type: 'string',
			default: '',
			description: 'Locations to exclude (semicolon separated)',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Keyword Tags',
			name: 'qOrganizationKeywordTags',
			type: 'string',
			default: '',
			description: 'Keywords associated with companies (semicolon separated)',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Organization Name',
			name: 'qOrganizationName',
			type: 'string',
			default: '',
			description: 'Filter by company name',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Min Latest Funding',
			name: 'latestFundingAmountRangeMin',
			type: 'number',
			default: 0,
			description: 'Minimum amount of most recent funding',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Max Latest Funding',
			name: 'latestFundingAmountRangeMax',
			type: 'number',
			default: 0,
			description: 'Maximum amount of most recent funding',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Min Total Funding',
			name: 'totalFundingRangeMin',
			type: 'number',
			default: 0,
			description: 'Minimum total funding amount',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Max Total Funding',
			name: 'totalFundingRangeMax',
			type: 'number',
			default: 0,
			description: 'Maximum total funding amount',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Latest Funding Date Min',
			name: 'latestFundingDateRangeMin',
			type: 'dateTime',
			default: '',
			description: 'Earliest date of most recent funding',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Latest Funding Date Max',
			name: 'latestFundingDateRangeMax',
			type: 'dateTime',
			default: '',
			description: 'Latest date of most recent funding',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Job Titles',
			name: 'qOrganizationJobTitles',
			type: 'string',
			default: '',
			description: 'Job titles in active job postings (semicolon separated)',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Job Locations',
			name: 'organizationJobLocations',
			type: 'string',
			default: '',
			description: 'Locations of active job postings (semicolon separated)',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Min Active Jobs',
			name: 'organizationNumJobsRangeMin',
			type: 'number',
			default: 0,
			description: 'Minimum number of active job postings',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Max Active Jobs',
			name: 'organizationNumJobsRangeMax',
			type: 'number',
			default: 0,
			description: 'Maximum number of active job postings',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Job Posted At Min',
			name: 'organizationJobPostedAtRangeMin',
			type: 'dateTime',
			default: '',
			description: 'Earliest date jobs were posted',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		{
			displayName: 'Job Posted At Max',
			name: 'organizationJobPostedAtRangeMax',
			type: 'dateTime',
			default: '',
			description: 'Latest date jobs were posted',
			displayOptions: { show: { resource: ['organization'], operation: ['search'] } },
		},
		// Fields for Organization Enrich
		{
			displayName: 'Website Domain',
			name: 'organizationDomain',
			type: 'string',
			default: '',
			required: true,
			description: 'Company website domain to enrich',
			placeholder: 'example.com',
			displayOptions: {
				show: { resource: ['organization'], operation: ['enrich'] },
			},
		},
		{
			displayName: 'Apollo Organization ID',
			name: 'organizationId',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['organization'], operation: ['enrich'] } },
		},
		// Fields for Organization Bulk Enrich
		{
			displayName: 'Domains (JSON Array)',
			name: 'organizationDomainsJson',
			type: 'json',
			default: '["example.com"]',
			description: 'JSON array of up to 10 domains',
			required: true,
			displayOptions: { show: { resource: ['organization'], operation: ['bulkEnrich'] } },
		},
	],
};
